import { DummyProductType } from '../../types';

export const DUMMY_PRODUCT_ARRAY: DummyProductType[] = [
  {
    id: 1,
    title: 'Wireless Headphones',
    image: 'https://images.pexels.com/photos/610945/pexels-photo-610945.jpeg',
    price: 129.99,
    category: 'Electronics',
    rating: 4.5,
    inStock: true,
  },
  {
    id: 2,
    title: 'Smartwatch Pro',
    image: 'https://images.pexels.com/photos/32977238/pexels-photo-32977238.jpeg',
    price: 199.99,
    category: 'Wearables',
    rating: 4.8,
    inStock: false,
  },
  {
    id: 3,
    title: 'Gaming Mouse',
    image: 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg',
    price: 49.99,
    category: 'Accessories',
    rating: 4.2,
    inStock: true,
  },
  {
    id: 4,
    title: '4K Monitor',
    image:
      'https://d12a36ei86qcqy.cloudfront.net/media/catalog/product/cache/74ae05ef3745aec30d7f5a287debd7f5/m/o/monitor-s2725qc-gray-gallery-1.jpg',
    price: 299.99,
    category: 'Displays',
    rating: 4.7,
    inStock: true,
  },
  {
    id: 5,
    title: 'Mechanical Keyboard',
    image: 'https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg',
    price: 89.99,
    category: 'Accessories',
    rating: 4.6,
    inStock: true,
  },
  {
    id: 6,
    title: 'Bluetooth Speaker',
    image: 'https://images.pexels.com/photos/1706694/pexels-photo-1706694.jpeg',
    price: 59.99,
    category: 'Audio',
    rating: 4.3,
    inStock: true,
  },
  {
    id: 7,
    title: 'Fitness Tracker Band',
    image: 'https://m.media-amazon.com/images/I/71CQ6esBqFL.jpg',
    price: 79.99,
    category: 'Wearables',
    rating: 4.0,
    inStock: false,
  },
  {
    id: 8,
    title: 'Tablet Stand',
    image: 'https://images.pexels.com/photos/6373028/pexels-photo-6373028.jpeg',
    price: 25.0,
    category: 'Accessories',
    rating: 4.1,
    inStock: true,
  },
  {
    id: 9,
    title: 'USB-C Hub',
    image: 'https://images.pexels.com/photos/4195398/pexels-photo-4195398.jpeg',
    price: 39.99,
    category: 'Electronics',
    rating: 4.4,
    inStock: true,
  },
  {
    id: 10,
    title: 'Portable SSD 1TB',
    image: 'https://images.pexels.com/photos/13595095/pexels-photo-13595095.jpeg',
    price: 149.99,
    category: 'Storage',
    rating: 4.9,
    inStock: true,
  },
];
